In [4]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [5]:
df=pd.read_csv('../Datasets/Mushrooms/mushrooms.csv')
df.head()

type cap_shape cap_surface cap_color bruises odor gill_attachment  \
0    p         x           s         n       t    p               f   
1    e         x           s         y       t    a               f   
2    e         b           s         w       t    l               f   
3    p         x           y         w       t    p               f   
4    e         x           s         g       f    n               f   

  gill_spacing gill_size gill_color  ... stalk_surface_below_ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk_color_above_ring stalk_color_below_ring veil_type veil_color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring_number ring_type spore_print_color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

# Convert Categorical data into numerical data

In [14]:
le=LabelEncoder()
ds=df.apply(le.fit_transform)
print(type(ds))

<class 'pandas.core.frame.DataFrame'>


In [15]:
ds.head()

type  cap_shape  cap_surface  cap_color  bruises  odor  gill_attachment  \
0     1          5            2          4        1     6                1   
1     0          5            2          9        1     0                1   
2     0          0            2          8        1     3                1   
3     1          5            3          8        1     6                1   
4     0          5            2          3        0     5                1   

   gill_spacing  gill_size  gill_color  ...  stalk_surface_below_ring  \
0             0          1           4  ...                         2   
1             0          0           4  ...                         2   
2             0          0           5  ...                         2   
3             0          1           5  ...                         2   
4             1          0           4  ...                         2   

   stalk_color_above_ring  stalk_color_below_ring  veil_type  veil_color  \
0                       7                       7          0           2   
1                       7                       7          0           2   
2                       7                       7          0           2   
3                       7                       7          0           2   
4                       7                       7          0           2   

   ring_number  ring_type  spore_print_color  population  habitat  
0            1          4                  2           3        5  
1            1          4                  3           2        1  
2            1          4                  3           2        3  
3            1          4                  2           3        5  
4            1          0                  3           0        1  

[5 rows x 23 columns]

In [21]:
data=ds.values
print(data.shape)
print(data[:5,:])

(8124, 23)
[[1 5 2 4 1 6 1 0 1 4 0 3 2 2 7 7 0 2 1 4 2 3 5]
 [0 5 2 9 1 0 1 0 0 4 0 2 2 2 7 7 0 2 1 4 3 2 1]
 [0 0 2 8 1 3 1 0 0 5 0 2 2 2 7 7 0 2 1 4 3 2 3]
 [1 5 3 8 1 6 1 0 1 5 0 3 2 2 7 7 0 2 1 4 2 3 5]
 [0 5 2 3 0 5 1 1 0 4 1 3 2 2 7 7 0 2 1 0 3 0 1]]


In [22]:
data_x=data[:,1:]
data_y=data[:,0]

In [24]:
x_train,x_test,y_train,y_test=train_test_split(data_x,data_y,test_size=0.2)
print(x_train.shape,x_test.shape)
print(y_train.shape,y_test.shape)

(6499, 22) (1625, 22)
(6499,) (1625,)


In [25]:
np.unique(y_train)

array([0, 1])

# Naive Bayes Classifier

In [29]:
y=np.array([1,0,1,1,0,0,0,1,0]);
np.sum(y==0)


5

In [38]:
def prior(y_train,label):
    num=np.sum(y_train==label)
    den=y_train.shape[0]
    return num/float(den)

def cond_prob(x_train,y_train,feature_col,feature_val,label):
    x_filtered=x_train[y_train==label]
    num=np.sum(x_filtered[:,feature_col]==feature_val)
    den=x_filtered.shape[0]
    return num/float(den)
    
def predict(x_train,y_train,x_test):
    
    classes=np.unique(y_train)
    n_features=x_train.shape[1]
    post_prob=[]
    
    for label in classes:
        
        likelihood=1.0
        for f in range(n_features):
            cond=cond_prob(x_train,y_train,f,x_test[f],label)
            likelihood*=cond

        p=prior(y_train,label)
        post=likelihood*p
        post_prob.append(post)
    
    pred=np.argmax(post_prob)
    return pred


In [52]:
z=0
op=predict(x_train,y_train,x_test[z])
print(op)
print(y_test[z])

1
1


In [53]:
def score(x_train,y_train,x_test,y_test):
    pred=[]
    for i in range(x_test.shape[0]):
        p=predict(x_train,y_train,x_test[i])
        pred.append(p)
    pred=np.array(pred)
    accuracy=np.sum(pred==y_test)/y_test.shape[0]
    return accuracy

In [54]:
print(score(x_train,y_train,x_test,y_test))

0.9963076923076923
